// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANGfd10kLzYBeRXhJW6pwYrtf3RpXq8kM',
    appId: '1:762713879415:web:3c94d485b4dd2e88cd6772',
    messagingSenderId: '762713879415',
    projectId: 'event-app-6eff4',
    authDomain: 'event-app-6eff4.firebaseapp.com',
    storageBucket: 'event-app-6eff4.firebasestorage.app',
    measurementId: 'G-HW287P0VEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxMSlXEymVtnE70Pz05HXD3jIxGDRB-E',
    appId: '1:762713879415:android:1d422dca3bc9e73ccd6772',
    messagingSenderId: '762713879415',
    projectId: 'event-app-6eff4',
    storageBucket: 'event-app-6eff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBucKgCIG2suA5VTNqsNnu8UYCgYqjjifQ',
    appId: '1:762713879415:ios:a9a40922935b029ecd6772',
    messagingSenderId: '762713879415',
    projectId: 'event-app-6eff4',
    storageBucket: 'event-app-6eff4.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBucKgCIG2suA5VTNqsNnu8UYCgYqjjifQ',
    appId: '1:762713879415:ios:a9a40922935b029ecd6772',
    messagingSenderId: '762713879415',
    projectId: 'event-app-6eff4',
    storageBucket: 'event-app-6eff4.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANGfd10kLzYBeRXhJW6pwYrtf3RpXq8kM',
    appId: '1:762713879415:web:89b7398f11e53ddecd6772',
    messagingSenderId: '762713879415',
    projectId: 'event-app-6eff4',
    authDomain: 'event-app-6eff4.firebaseapp.com',
    storageBucket: 'event-app-6eff4.firebasestorage.app',
    measurementId: 'G-DYL50L77J2',
  );
}
